export interface UseCaseDoc {
  slug: string;
  title: string;
  tagline: string;
  tag: string;
  accent: string;
  video?: string;
  poster?: string;
  body: string[];
}

export const useCases: Record<string, UseCaseDoc> = {
  "coding-agents": {
    slug: "coding-agents",
    title: "Coding agents",
    tagline:
      "Run Claude Code, Codex, or a local Pi subprocess against your codebase with real file tools, a transcript you can read, and undo a few clicks away.",
    tag: "Use case · Engineering",
    accent: "#D7EFD3",
    body: [
      "## What you wire up",
      "A coding session in Froots is just chat with the right backend and the right skills enabled. Claude Code and Codex both run as one-shot subprocesses; Pi runs as a long-lived process that keeps multi-turn memory between prompts.",
      "The agent gets a workspace-scoped set of file tools: `agent_read_doc`, `agent_write_doc`, and `agent_edit_doc` (strict one-match substring replace, so the model can&rsquo;t make ambiguous edits). Everything is bounded to your workspace folder.",
      "## Skills that pair well",
      "- **`github`** — read, comment, and ship PRs via the `gh` CLI.",
      "- **`coding-agent`** — Froots&rsquo;s shipped guidance for code-writing flows.",
      "- **`safe-file-deletion`** — always-on; gates destructive ops behind a confirm step.",
      "- **`tmux`** — drive a terminal session if you want long-running processes outside the agent loop.",
      "## What it looks like in practice",
      "> [check green] **Steerable.** Every tool call streams into the UI as a bubble. You can pause, cancel, and rerun mid-stream — the agent doesn&rsquo;t silently do twenty things behind your back.",
      "Pair it with the `Careful` permission policy and Froots will prompt before any edit. Pair it with `Yolo` and it just rips.",
      "## What it doesn&rsquo;t replace",
      "Froots isn&rsquo;t an IDE. It runs alongside your editor, owns the agent loop, and writes to disk; you commit the diffs in git on your own terms. Reasoning/thinking event surfacing for Claude/Codex is still in flight.",
    ],
  },
  "browser-automations": {
    slug: "browser-automations",
    title: "Browser automations",
    tagline:
      "Hand the agent a browser. It opens pages, clicks, fills forms, and screenshots — and you watch the live session.",
    tag: "Use case · Automation",
    accent: "#5191F8",
    body: [
      "## What powers it",
      "Browser automation in Froots is wrapped around the `agent-browser` CLI — a Playwright-driven binary that exposes browser primitives as agent tools. The `browser-automation` skill is one of the three hardcoded system skills; it&rsquo;s gated on the `agent-browser` binary being present and toggleable from the Skills tab.",
      "The agent gets six tool calls: `browser_open`, `browser_snapshot`, `browser_click`, `browser_fill`, `browser_screenshot`, `browser_scroll`. Each call streams into the UI so you can see what the agent saw at every step.",
      "## What it&rsquo;s good at",
      "- **One-off scrapes** — go to a site, pull the table, drop it in a note.",
      "- **Multi-page workflows** — search results → click result → extract → repeat.",
      "- **Form filling** — fill the application, capture a screenshot, submit on your approval.",
      "- **Visual verification** — &ldquo;does the staging site actually render correctly?&rdquo;",
      "## Watch and intervene",
      "> [zap blue] **Live observability.** Every snapshot is rendered in the chat surface. If the agent gets stuck on a dropdown or hits a captcha, you take over without losing the run.",
      "## What it isn&rsquo;t",
      "Not a headless scraper for millions of pages. The browser runs locally with one tab; this is one agent, one session, watching what it&rsquo;s doing.",
    ],
  },
  "research-agents": {
    slug: "research-agents",
    title: "Research agents",
    tagline:
      "Multi-step deep dives with citations. The agent does the legwork; you read the brief.",
    tag: "Use case · Research",
    accent: "#FBD9DA",
    body: [
      "## The shape",
      "A research run is usually one prompt — &ldquo;survey the state of X, cite sources, give me a 1-page brief&rdquo; — handed to an assistant with research-flavored skills enabled. The agent uses the browser, summarizes findings, and writes the result back into your workspace.",
      "## Skills that pair well",
      "- **`browser-automation`** — open, search, scroll, screenshot.",
      "- **`summarize`** — condense long pages and transcripts.",
      "- **`openai-whisper`** — transcribe video or podcast sources before summarizing.",
      "- **`obsidian`** — if your vault is your second brain, drop the brief there with backlinks.",
      "## What ends up in memory",
      "Every brief the agent writes lands in `workspace/memory/` or `workspace/kb/` as a markdown file. The indexer chunks it and adds it to the vector store, so the next research run can pull the previous findings as context automatically.",
      "> [database pink] **Compounding research.** The graph view of memories starts looking interesting around brief 10. Clusters form around topics you keep returning to.",
      "## Schedule it",
      "Pair this with a **routine** to wake the agent up weekly and produce a new edition of the brief. The schedule type is `Weekly`; the prompt is the same one you&rsquo;d type by hand.",
    ],
  },
  "sales-outbound": {
    slug: "sales-outbound",
    title: "Sales & outbound",
    tagline:
      "Source leads, enrich them, draft outreach in your voice, and log everything you can audit.",
    tag: "Use case · Sales",
    accent: "#5191F8",
    body: [
      "## The flow",
      "Froots doesn&rsquo;t ship a CRM. It ships the tools and skills you need to drive whichever one you already use. A sales run is usually three pieces wired together: a lookup step, a draft step, and a logging step.",
      "## Skills that pair well",
      "- **`browser-automation`** — pull lead context from LinkedIn, company sites, or your CRM&rsquo;s web UI.",
      "- **`slack`** or **`imsg`** / **`signal`** / **`telegram`** — send the actual outreach where your contacts live.",
      "- **`1password`** — fetch API keys for paid lookup services without leaking them into the prompt.",
      "- **`apple-notes`** or **`obsidian`** — your call-prep doc lives in your second brain, not in the CRM.",
      "## Drafts, not sends",
      "> [check green] **Draft mode by default.** Run the agent on `Careful` permissions for outbound. The agent writes drafts, files them in a queue, and waits for your approval before anything ships.",
      "## Routines that fit",
      "- A morning routine that pulls overnight inbound replies and drafts responses for review.",
      "- A weekly routine that re-runs your lead-scoring prompt against the last seven days of activity.",
    ],
  },
  "data-extraction": {
    slug: "data-extraction",
    title: "Data extraction",
    tagline:
      "Point an agent at a site and get clean structured data back. No scrapers, no brittle selectors — the run is the spec.",
    tag: "Use case · Data",
    accent: "#D7EFD3",
    body: [
      "## How it&rsquo;s different from a scraper",
      "Traditional scrapers break the day the site changes a class name. An agent-driven extraction describes the *intent* (&ldquo;get the product price, the SKU, and the in-stock status from each tile&rdquo;) and lets the model adapt to whatever the page actually looks like today.",
      "## What it uses",
      "- **`browser-automation`** to drive the page.",
      "- **`agent_write_doc`** to dump structured output (JSON, markdown table, CSV) into your workspace.",
      "- **`browser_snapshot`** at each step so you can audit what the agent actually saw before it wrote anything.",
      "## A good shape",
      "Tell the agent: _&ldquo;Visit `<url>`, pull every row from the listings table into `workspace/extracts/{date}-listings.json`, and stop if the row count is below 10 — flag it for review instead.&rdquo;_",
      "> [database green] **The output lands in memory.** Once the JSON is in the workspace, the indexer chunks and embeds it. Future agents can ask &ldquo;what did we see last Tuesday?&rdquo; without re-running the extraction.",
      "## When to fall back",
      "If you need millions of pages, you want a real scraper. Agent-driven extraction is best at moderate scale, irregular pages, and one-shot tasks where the cost of writing brittle selectors exceeds the cost of an LLM call.",
    ],
  },
  "customer-support": {
    slug: "customer-support",
    title: "Customer support",
    tagline:
      "Triage tickets, draft replies grounded in your KB, and route the hard ones back to a human — with a full transcript of every step.",
    tag: "Use case · Support",
    accent: "#FBD9DA",
    body: [
      "## The pieces",
      "A support agent in Froots usually combines a knowledge base (your workspace `kb/` folder), a messaging skill for the channel where tickets arrive, and a memory of past resolutions.",
      "## Skills that pair well",
      "- **`slack`** — most teams triage support in a shared channel.",
      "- **`imsg`** / **`signal`** / **`telegram`** — for direct customer threads.",
      "- **`summarize`** — to compress long ticket threads before drafting.",
      "- The agent reads your **`kb/`** folder via `agent_read_doc` — any markdown you drop in there becomes citable.",
      "## Why memory matters here",
      "Every time you resolve a ticket and write a note about how, it becomes a node the indexer can surface for similar future tickets. The vector store ranks by cosine similarity at a 0.45 threshold, so on the next round the agent doesn&rsquo;t need to re-derive the answer.",
      "> [check pink] **Draft, never auto-send.** Support is the canonical case for `Careful` permissions. The agent triages and drafts; a human approves and ships.",
      "## A useful routine",
      "Every two hours during business hours, sweep new tickets, group them by topic, and post a one-line summary of pending threads to the team channel. Cron: `0 9-17/2 * * 1-5`.",
    ],
  },
  "ops-internal-tools": {
    slug: "ops-internal-tools",
    title: "Ops & internal tools",
    tagline:
      "Morning briefs, weekly reports, scheduled cleanups. Give an agent the tools and a cron, then forget about it.",
    tag: "Use case · Ops",
    accent: "#D7EFD3",
    body: [
      "## What this category covers",
      "Anything that runs on a schedule and produces a document, a notification, or a small action. Ops work tends to be repetitive, low-stakes per run, and high-value in aggregate — exactly what routines are built for.",
      "## Routines that pay rent",
      "- **Morning briefing** — daily 07:30. Pull calendar, tickets, overnight mail, write `today.md`.",
      "- **Weekly retro** — Fridays 16:30. Group the week&rsquo;s notes into wins / unsolved / next-week, append to `retros/{date}.md`.",
      "- **Inbox sweep** — every 30 minutes. Triage new messages and draft replies; never auto-send.",
      "- **Stale-ticket digest** — daily 17:00. Pull tickets with no activity for 7+ days and post a list to Slack.",
      "## Skills that pair well",
      "- **`github`** for PR/issue housekeeping.",
      "- **`slack`** for posting summaries where the team reads.",
      "- **`linear`-flavored prompts** via the `github` and browser skills if you don&rsquo;t have a dedicated one yet.",
      "## Heartbeat fits here too",
      "> [zap green] **Proactive ops.** Enable heartbeat on the assistant that owns these routines. Between scheduled runs, it can check in on its own and surface anything urgent — only when it&rsquo;s actually worth surfacing.",
    ],
  },
  "marketing-content": {
    slug: "marketing-content",
    title: "Marketing & content",
    tagline:
      "Competitor tracking, content drafts, scheduling — agents handle the busywork while you keep editorial control.",
    tag: "Use case · Marketing",
    accent: "#FBD9DA",
    body: [
      "## What you can offload",
      "Most marketing work splits into two buckets: tracking what&rsquo;s happening (competitors, mentions, trends) and producing what goes out (drafts, variations, schedules). Froots handles the first well and the second usefully — once you&rsquo;ve trained it on your voice.",
      "## Skills that pair well",
      "- **`browser-automation`** to watch competitor sites and social feeds.",
      "- **`summarize`** to compress long-form sources into beats you can riff on.",
      "- **`openai-image-gen`** / **`nano-banana-pro`** for visual drafts.",
      "- **`obsidian`** to keep an editorial calendar and a brand-voice document the agent can read every run.",
      "## A useful routine",
      "Daily at 09:00: pull the three competitor blogs from `memory/competitors.md`, summarize anything new, and append it to `workspace/marketing/inbound.md` with one-line takes.",
      "> [lightbulb pink] **Voice doc beats voice prompt.** Drop a `brand-voice.md` in your workspace describing tone, things-we-say, things-we-don&rsquo;t. The indexer surfaces it on every relevant turn — you don&rsquo;t have to re-prompt the voice each time.",
      "## What you still own",
      "Final edits, channel choice, and timing. The agent drafts; you ship.",
    ],
  },
  "personal-assistant": {
    slug: "personal-assistant",
    title: "Personal assistant",
    tagline:
      "Your calendar, your messages, your notes, your smart home — driven by one agent that knows your schedule and your taste.",
    tag: "Use case · Personal",
    accent: "#D7EFD3",
    body: [
      "## The shape",
      "A personal assistant in Froots is one assistant with broad skill coverage, an opinionated `context.md`, and heartbeat enabled. You tell it who you are once; it tunes the rest.",
      "## Skills that pair well",
      "- **`apple-notes`** / **`bear-notes`** / **`things-mac`** — native capture for whatever you already use.",
      "- **`apple-reminders`** — write actionable items as reminders instead of free-form notes.",
      "- **`spotify-player`** / **`sonoscli`** — music and speakers.",
      "- **`openhue`** / **`wyze`** — lights, cameras.",
      "- **`weather`** — current conditions and forecasts surface in briefings.",
      "- **`imsg`** / **`signal`** — read and write in your messaging channels.",
      "## Where memory earns its keep",
      "The `context.md` file is the bedrock here. It holds the durable stuff: your name, your role, the people you talk to most, your meeting cadences, what you don&rsquo;t want surfaced. Every routine reads it. Heartbeat updates it.",
      "> [brain green] **Tune `context.md` once.** Drop in things like &ldquo;don&rsquo;t notify me about marketing emails&rdquo; or &ldquo;morning briefings should mention if it&rsquo;s a gym day.&rdquo; The agent reads it on every turn and the behavior just changes.",
      "## A routine that ties it together",
      "Daily 06:45. Check tomorrow&rsquo;s calendar, check weather, check overnight messages from people in your contacts whitelist, queue a Spotify playlist that fits the day, and draft a one-page brief into `today.md`. You read it with coffee.",
    ],
  },
  "knowledge-base": {
    slug: "knowledge-base",
    title: "Knowledge base",
    tagline:
      "Turn your scattered docs, meetings, and notes into a searchable second brain. The vector store does the indexing; you keep editing markdown.",
    tag: "Use case · Knowledge",
    accent: "#FBD9DA",
    body: [
      "## How Froots handles a KB",
      "Drop markdown into `workspace/kb/` and the indexer chunks it by heading, embeds each chunk with BGE-small (384 dimensions), and stores it in a libsql DiskANN index. On every prompt, the top-K most similar chunks (default 8, similarity ≥ 0.45) are injected into the system prompt.",
      "There&rsquo;s no extra setup. Save a file, the watcher notices, the indexer runs in the background.",
      "## Skills that pair well",
      "- **`obsidian`** — point Froots at your vault and the indexer covers it.",
      "- **`notion`** — pull pages out of Notion into local markdown for indexing.",
      "- **`summarize`** — compress long sources into shorter chunks before they hit the KB.",
      "- **`openai-whisper`** — transcribe audio sources first so the text can be indexed.",
      "## Where this beats a cloud KB",
      "- **It&rsquo;s local.** No upload, no third party, no annual cost. The libsql file lives next to the app.",
      "- **It&rsquo;s plain markdown.** You can edit, diff, and version-control it.",
      "- **It&rsquo;s queryable by your agent.** Not just text-search — the model gets the relevant chunks in context every turn.",
      "> [database pink] **The KB and your conversations share the same index.** A note you wrote last month and a chat from this morning are both surfaced by the same retrieval call, ranked by similarity.",
      "## What&rsquo;s missing (today)",
      "Recency decay, citations-back-to-source-line, and a polished &ldquo;ask the KB&rdquo; query UI aren&rsquo;t shipped yet. Today this is a workflow built on chat + indexed markdown, not a dedicated product surface.",
    ],
  },
  "voice-agents": {
    slug: "voice-agents",
    title: "Voice & audio agents",
    tagline:
      "Transcribe meetings, summarize calls, generate voice notes — turn audio into text the rest of the system can act on.",
    tag: "Use case · Voice",
    accent: "#5191F8",
    body: [
      "## The pipeline",
      "Audio in Froots flows through two skills: `openai-whisper` for transcription (local model) or `openai-whisper-api` (cloud), then `summarize` to compress the transcript into something useful. Output is plain markdown, indexed like anything else in your workspace.",
      "## What you can wire up",
      "- **Meeting capture** — point the agent at an audio file or a Zoom recording, get a transcript + summary + action items in `workspace/meetings/{date}.md`.",
      "- **Voice notes** — record a thought on your phone, drop it in a watched folder, the agent transcribes and files it.",
      "- **Podcast research** — transcribe an episode, surface the bits relevant to a topic you&rsquo;re researching.",
      "## Local vs cloud",
      "| Path | Pros | Cons |\n| --- | --- | --- |\n| `openai-whisper` (local) | Free, private, no internet | Slower, model download |\n| `openai-whisper-api` | Fast, accurate | Costs cents per file, leaves your machine |",
      "> [zap blue] **Both ship.** Pick per-task. Sensitive meeting? Local. Quick lunchtime podcast? API.",
      "## Output is markdown — so the rest works",
      "Once the transcript is in the workspace, every other Froots primitive applies. The KB indexer picks it up. Routines can summarize it weekly. Memory recall surfaces it next time you ask about the topic.",
    ],
  },
  "evals-qa": {
    slug: "evals-qa",
    title: "Evals & QA",
    tagline:
      "Run an agent across a dataset, replay any case, and diff outputs between harnesses or model versions to see what actually got better.",
    tag: "Use case · Evals",
    accent: "#5191F8",
    body: [
      "## What Froots gives you for evals",
      "Every session, tool call, and message snapshot is persisted in the local database. The `sessions` table holds `messages_json` per run; `agent_tool_calls` records every tool invocation. That&rsquo;s the substrate evals work on.",
      "## The shape of an eval",
      "- Build a list of prompts (a markdown file works; one per line, or one per file).",
      "- Run a routine with `Interval` scheduling that picks the next un-evaluated prompt, runs it, and writes the output to `workspace/evals/{run-id}/{case}.md`.",
      "- Pull the resulting set of files into a comparison view, or have a second routine grade them.",
      "## What you can diff",
      "- **Across backends** — same prompt against Claude vs Codex vs Pi.",
      "- **Across models** — switch backend model and re-run.",
      "- **Across skills** — toggle a skill off and see which cases regress.",
      "- **Across permissions** — `Careful` vs `Balanced` vs `Yolo` produces different shapes of run.",
      "> [graph blue] **Replay any case.** Sessions are stored intact. Open one, scroll the tool calls, and rerun the prompt with one change — same memory, same skills, different model. That&rsquo;s the eval loop.",
      "## What&rsquo;s missing",
      "A first-class eval UI isn&rsquo;t shipped — today this is a workflow built on top of routines and the sessions store. If you want it polished, it&rsquo;s on the roadmap.",
    ],
  },
};

export function getUseCase(slug: string): UseCaseDoc | undefined {
  return useCases[slug];
}

export const useCaseOrder = [
  "coding-agents",
  "browser-automations",
  "research-agents",
  "sales-outbound",
  "data-extraction",
  "customer-support",
  "ops-internal-tools",
  "marketing-content",
  "evals-qa",
  "personal-assistant",
  "knowledge-base",
  "voice-agents",
];
